import { Link as RouterLink } from "react-router-dom";
import type { Locale } from "@htp/i18n";
import type { PageProps } from "./App";
import { Alert,Badge,Button,Callout,Card,Container,CorrectionNotice,Divider,EvidenceLevel,Heading,SourceReference,Stack,Text,UncertaintyNotice,VersionInformation } from "./design-system/components";
import { demoModule } from "./knowledge/demo";

const local=(value:Record<Locale,string>,locale:Locale)=>value[locale];
export function HomePage({t}:PageProps){return <Container><section className="hero"><Text className="eyebrow">{t("app.milestone")}</Text><Heading level={1}>{t("app.title")}</Heading><Text className="lead">{t("app.description")}</Text><Callout title={t("status.title")}>{t("app.phase")}</Callout></section><Heading level={2}>{t("principles.title")}</Heading><div className="grid"><Card><Badge>01</Badge><Text>{t("principles.inform")}</Text></Card><Card><Badge>02</Badge><Text>{t("principles.document")}</Text></Card><Card><Badge>03</Badge><Text>{t("principles.remind")}</Text></Card></div></Container>}
export function KnowledgePage({t}:PageProps){return <Container><Stack gap="6"><Heading level={1}>{t("knowledge.title")}</Heading><Text>{t("knowledge.intro")}</Text><Card><Badge tone="info">{t("knowledge.demoBadge")}</Badge><Heading level={2}>{t("knowledge.demoTitle")}</Heading><Text>{t("knowledge.demoSummary")}</Text><RouterLink className="ds-link" to="/knowledge/how-to-read-a-module">{t("knowledge.open")}</RouterLink></Card></Stack></Container>}
export function ModulePage({locale,t}:PageProps){const m=demoModule;return <Container><Stack gap="6"><header><Badge tone="info">{t("knowledge.demoBadge")}</Badge><Heading level={1}>{local(m.title,locale)}</Heading><Text className="lead">{local(m.summary,locale)}</Text><VersionInformation version={m.version} date={m.last_reviewed} versionLabel={t("module.version")} dateLabel={t("module.updated")}/></header><div className="module-layout"><nav className="toc" aria-label={t("module.contents")}><Heading level={2}>{t("module.contents")}</Heading><ul>{m.sections.map(s=><li key={s.id}><a href={`#${s.id}`}>{local(s.heading,locale)}</a></li>)}<li><a href="#sources">{t("module.sources")}</a></li></ul></nav><Stack gap="8"><EvidenceLevel label={t("module.evidence")} detail={local(m.evidence_overview,locale)} disclaimer={t("module.evidenceDisclaimer")}/><UncertaintyNotice title={t("module.uncertainty")} disclaimer={t("module.uncertaintyDisclaimer")}><Text>{local(m.uncertainties[0],locale)}</Text></UncertaintyNotice><Alert>{local(m.safety_notes[0],locale)}</Alert>{m.sections.map(s=><section className="content-section" id={s.id} key={s.id}><Heading level={2}>{local(s.heading,locale)}</Heading><Text>{local(s.body,locale)}</Text></section>)}<Divider/><section id="sources"><Heading level={2}>{t("module.sources")}</Heading><ol>{m.sources.map(s=><SourceReference key={s.source_id} id={s.source_id} title={`${s.title} (${s.year})`} href={s.url}/>)}</ol></section><section><Heading level={2}>{t("module.editorial")}</Heading><Text>{m.authors.join(", ")} · {m.reviewers.join(", ")}</Text><Badge tone="success">{t("module.translation")}: {t(`translation.${m.translation_status[locale]}`)}</Badge></section><CorrectionNotice title={t("module.correction")}>{local(m.correction_history[0].note,locale)} · {m.correction_history[0].date}</CorrectionNotice></Stack></div></Stack></Container>}
export function DesignSystemPage({t}:PageProps){return <Container><Stack gap="6"><Heading level={1}>{t("design.title")}</Heading><Text>{t("design.intro")}</Text><div className="grid"><Card><Heading level={2}>{t("design.card")}</Heading><Badge tone="info">{t("design.badge")}</Badge><Text>{t("design.neutral")}</Text><Button>{t("design.button")}</Button></Card><Callout title={t("design.info")}>{t("design.infoText")}</Callout><UncertaintyNotice title={t("module.uncertainty")} disclaimer={t("module.uncertaintyDisclaimer")}><Text>{t("design.uncertaintyText")}</Text></UncertaintyNotice></div></Stack></Container>}
export function NotFoundPage({t}:PageProps){return <Container><section className="not-found"><Heading level={1}>{t("notFound.title")}</Heading><Text>{t("notFound.text")}</Text><RouterLink className="ds-link" to="/">{t("notFound.home")}</RouterLink></section></Container>}
